### PR TITLE
Openal soft

### PR DESCRIPTION
**Pull request by LinuxDonald**
@jakoch could you please review it before i merge this?

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Needs rebase....

**Comment by jakoch** [comment]
- linux + windows: ok
- but it's still not picked up on Mac
   - https://travis-ci.org/fifengine/fifengine/jobs/207739613#L1326
     - it still uses the system location: `Found OPENALSOFT: /System/Library/Frameworks/openal.framework` instead of the installed dependency     
   - https://travis-ci.org/fifengine/fifengine/jobs/207739612#L1036
We need to guide the finder using the provided pkg-config: https://travis-ci.org/fifengine/fifengine/jobs/207739612#L1048

**Comment by LinuxDonald** [comment]
finally done. Review and rebase please @jakoch :)

**Comment by jakoch** [comment]
ah, finally it's found `/usr/local/opt/openal-soft/lib/libopenal.dylib`. 
good job.

**Pull request merged**
