### PR TITLE
appveyor setup

### PR DESCRIPTION
**Pull request by jakoch**
- several bugfixes for errors, which blocked compilation, see https://github.com/fifengine/fifengine/issues/905
- removal of internal TinyXML (engine/core/ext/tinyxml), see https://github.com/fifengine/fifengine/issues/903
- general cleanup of the CMakeList.txt
- added appveyor toolchain for VC builds 
- independent CMakeList.txt for 3th party dependencies (see /dependencies folder)
  - including getter/build scripts for the 3th party dependencies
    - fifechan
    - libogg
    - libpng
    - libvorbis
    - openal
    - sdl2
    - sdl2_image
    - sdl2_ttf
    - swig
    - tinyxml
    - zlib
- updated readme
  - added build status table
  - added project links
- converted Changelog to markdown
- added automatic deployment of artifacts to Appveyor
    - https://ci.appveyor.com/project/jakoch/fifengine/build/artifacts
    - dev-builds are released with "dev-commit" suffix, referencing #888 (Nightly builds)
- added automatic deployment of artifacts to Github Releases (Not tested)

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@jakoch maybe squash some commits that it is not so big?
And are you done here? Then i would merge it.

**Comment by jakoch** [comment]
> maybe squash some commits that it is not so big?

Ok, i will squash some trial and error commits.

> And are you done here? 

Well, that depends on the outcome of the discussion over at #907 (how to package fife correctly?).
I simply don't know if the produced artifacts are ok...

When the artifacts are ok, i would like to proceed bundling all the stuff and building the "fife-sdk".

**Comment by jakoch** [comment]
Ok, build is green on Appveyor: https://ci.appveyor.com/project/jakoch/fifengine/build/dev-9ba4568#L88

**Comment by jakoch** [comment]
build is green and artifacts are produced: https://ci.appveyor.com/project/jakoch/fifengine/build/artifacts
i think i'm done for now and it's ready for review.

**Comment by LinuxDonald** [comment]
I will merge that tomorrow. Because this pr gets bigger and bigger. After the merge you could create an new pr :)

**Comment by jakoch** [comment]
> Because this pr gets bigger and bigger. 

True. But it reflects the amount of time and work invested. 
I squashed today's trial and error commits down into 3 commits.

It includes a lot of stuff: cleanups, bugfixes, cmake, dependencies fetching and building.
And additional changes based one the feedback i got for building the artifacts correctly.

**Comment by LinuxDonald** [comment]
Yeah you have done alot of work thx for this :) You helped us very much :) Thank you :)

**Comment by jakoch** [comment]
Glad i could help.
I've some more things on my todo list, but the things had and have to be done in order.
Fifechan cleanup -> toolchain -> Artifacts, then Fifeengine cleanup ->toolchain -> Artifacts
Finally, i can start on the installer for the new Fife-SDK, re-using the dependency artifacts and builds from both repositories combined with the build-tools. Then a documentation toolchain, because this thing has no manual and the docs i ran into, while working on the toolchains are pretty much outdated.

**Comment by LinuxDonald** [comment]
Thank you again for this work :) Now you can start to work on the net BIG pr :) :+1:

**Pull request merged**
