### PR TITLE
remove librocket [Dont merge for 0.4.0]

### PR DESCRIPTION
**Pull request by LinuxDonald**
remove librocket

@jakoch i started work on it. Not tested it yet. And maybe i dont found all what must be delete.

@Beliaar @Niektory do one of you use librocket?

### CODE REVIEW

**Comment by prock-fife** [comment]
Whats the reasoning behind removing librocket?  The idea is to allow clients to choose which UI to use so we've included several interfaces.    I wouldn't say we need to ship it in the pre-compiled versions of fife or the dev kit or anything.. just keep the interface around if they want to compile it themselves.

**Comment by LinuxDonald** [comment]
We dont have an maintainer for it. In the future we want to remove fifechan because it dont have any maintainer. And UH will (maybe) moved to cegui.
I and jakoch talked about it. And we are the only to active guys on the engine. We cant maintain something what is not used.

**Comment by helios2000** [comment]
I'm against that step. You don't know if a client use it or not. Beliar and Niektory are not the only people who use FIFE.
I'll maintain it as I have done in the past.
And the next step would be to remove the pathfinder because UH don't use it?

**Comment by LinuxDonald** [comment]
Okay I will close it. Yeah I think that uh use its own pathfinder.

**Pull request closed without merging**
