### PR TITLE
Add CMake support #886

### PR DESCRIPTION
**Pull request by LinuxDonald**
I think we should merge that into master.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Fixes #886

**Comment by prock-fife** [comment]
Seems that scons is broken since a27c5e4

We either need to fix it or clean it up to avoid confusion.  I would prefer to fix it and add a deprecated message.

**Comment by LinuxDonald** [comment]
@Beliaar have you maybe an fix for this problem?

**Comment by Beliaar** [comment]
Well, the fix would be to restore the version.h that was there before and keep version.h.in for cmake. There should be no conflicts with that since cmake will overwrite the existing file.

**Comment by LinuxDonald** [comment]
Could you do that on that branch please?

**Comment by LinuxDonald** [comment]
Now there is an new error.

**Comment by Beliaar** [comment]
which is?

**Comment by Beliaar** [comment]
Everything should be fixed now.

**Comment by vtchill** [comment]
Is this ready to be merged @Beliaar?

**Pull request merged**
