### PR TITLE
Add an option to setup.py to set package version from command line

### PR DESCRIPTION
**Pull request by Niektory**
For example:
python setup.py set_metadata --version=0.4.1 bdist_wininst

Issue #908

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@jakoch fix this your problem?

**Comment by jakoch** [comment]
Yes, this useful. Thanks for implementing, Niektory. 
Please merge this **after** my Appveyor PR.
Then we need one more commit on top to make use of it and inject the version.

**Comment by LinuxDonald** [comment]
Okay i will do it tomorrow.

**Comment by LinuxDonald** [comment]
@Niektory thx for this :) :+1:

**Pull request merged**
