### PR TITLE
Pythonize

### PR DESCRIPTION
**Pull request by LinuxDonald**
@Beliaar can that stuff merged or should we remove this branch?

### CODE REVIEW

**Comment by Beliaar** [comment]
I dont known anything about that branch,

**Comment by helios2000** [comment]
As discussed with prock, the problem is the documentation. The new functions will not be visible.

**Comment by LinuxDonald** [comment]
@Beliaar could you maybe fix the merge conflict here please?

**Comment by Beliaar** [comment]
@LinuxDonald I don't know what the code at those conflicts should do.

**Comment by LinuxDonald** [comment]
@helios2000 what about an merge an create an ticket that we need documantation for it?

**Comment by helios2000** [comment]
Our documentation is created automatically. But that would not work for the changes this branch brings. So we would first need to find a way how that could works.

**Pull request closed without merging**
