### PR TITLE
Merged Added modal focus functions to Pychan and enhanced ModalFocusE…

### PR DESCRIPTION
**Pull request by LinuxDonald**
…xample.

See: https://github.com/fifengine/fifechan/pull/26

### CODE REVIEW

**Comment by prock-fife** [comment]
odd..   travis tried to use clang to compile fife.  Did we change that?

**Comment by prock-fife** [comment]
Looking at the errors and it occurred to me that you probably have to update the swig interface files to add the additional fifechan functions.

**Comment by LinuxDonald** [comment]
Hmm I should take an look for this on helios changes maybe there are some swig changes.

**Comment by stubb** [comment]
Travis builds with clang and gcc. I changed that some months ago.

**Comment by LinuxDonald** [comment]
@prock-fife it compiles when you use fifechan with this pr: https://github.com/fifengine/fifechan/pull/26

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fifengine-demos/pull/3

With this pr Modalfocus should be testable. Not tested it yet.

**Pull request merged**
