### PR TITLE
Python3 [Work in Progress]

### PR DESCRIPTION
**Pull request by LinuxDonald**

### CODE REVIEW

**Comment by Beliaar** [comment]
I'd like to say that i am very unsure if we should already merge the branch into master already.

**Comment by LinuxDonald** [comment]
squidds is already working of the port of UH to python3: https://github.com/unknown-horizons/unknown-horizons/pull/2490

**Comment by LinuxDonald** [comment]
@Beliaar i dont want to merge it now into master. We from UH will do a lot of tests. And see if we find any erros and if it maybe breaks python2 support.

**Comment by prock-fife** [comment]
Just some notes... before we merge we need to make sure all other fife repos that use python (demos and editor for example) are also updated to use python3.

**Comment by LinuxDonald** [comment]
@prock-fife the python3 support will not break python2 support. Fife only needs to be compiled with python2

**Comment by jakoch** [comment]
@LinuxDonald We've already implemented support for both Python versions using `PythonInterp` + `PythonLibs`´.

Just speaking for the windows part:
We just need to add another build matrix entry, which uses Py3 and spits the installer out.
Then you get the py2.7 and py3 installer for each commit.

**Comment by LinuxDonald** [comment]
@Beliaar could you maybe please merge lastest master changes into the python3 branch?

**Pull request closed without merging**
