### PR TITLE
Change pychan font definitions to XML [NEEDS TO BE FIXED]

### PR DESCRIPTION
**Pull request by Drakekin**
Fixes issue #662

PyChan font definitions are now loaded from a file with the following definition:

``` xml
<fonts>
    <font name="pickbelt" type="truetype" size="13" color="255,255,255" source="content/fonts/LinLibertineB.ttf" antialias="1"/>
    <font name="default" type="truetype" size="15" color="68,42,2" source="content/fonts/LinLibertineI.ttf" antialias="1"/>
    <font name="default_bold" type="truetype" size="15" color="68,42,2" source="content/fonts/LinLibertineBI.ttf" antialias="1"/>
</fonts>
```

Fields from the old definition format are replaced one-to-one by attributes in the new format.

### CODE REVIEW

**Comment by LinuxDonald** [comment]
Any news here?

**Comment by prock-fife** [comment]
I had suggested a while back to throw an exception if someone tries to pass a fontdef file.   Instead we should retain the capability to load fontdef files but deprecate the functionality.  Can be removed completely in 0.4.1.  I'm not sure how to proceed with merging this.  Perhaps I'll merge into a new branch and fix it myself as I believe @Drakekin is no longer active.

**Comment by LinuxDonald** [comment]
@prock-fife i will split the pr into new branches one with the changes for fife and one new pr on the fife demos repo. Maybe when you find time you could make it final?

**Comment by LinuxDonald** [comment]
@prock-fife please check if i merged into an new branch correctly: https://github.com/fifengine/fifengine/pull/929

**Comment by LinuxDonald** [comment]
@prock-fife demos change pr is here: https://github.com/fifengine/fifengine-demos/pull/4

**Comment by helios2000** [comment]
See https://github.com/fifengine/fifengine/pull/1015

**Pull request closed without merging**
