### PR TITLE
Cegui sdk

### PR DESCRIPTION
**Pull request by LinuxDonald**
Add Cegui Support for Appveyor
And better support of cegui.

@Beliaar is this branch now rdy?

### CODE REVIEW

**Comment by Beliaar** [comment]
@LinuxDonald As far as I know it should work.

**Comment by LinuxDonald** [comment]
Do you know how we can disable it for travis build? Because they habe only an very old cegui version only and no python version of it.

**Comment by Beliaar** [comment]
I dont really know travis, sorry

**Comment by LinuxDonald** [comment]
Have we an cmake option to disable cegui?

**Comment by Beliaar** [comment]
The normal cmake build script for fife has an option to disable cegui. The appveyor script, however, does always build with cegui.

**Pull request merged**
