### PR TITLE
Native image cursor

### PR DESCRIPTION
**Pull request by Niektory**
Issue #1012 
This PR adds the native image cursor feature.
If enabled, cursors set to an image or an animation will be set using SDL and drawn by the native platform; otherwise they will be drawn by FIFE.
This setting has no effect on NativeCursor types which are always native and on the drag cursor which is always drawn by FIFE.
Animations are implemented by setting a new SDL cursor whenever the animation frame changes.
If creating the cursor fails we log the error and fall back to software cursor.

Animated cursors work fine when loaded with AnimationLoader, but when I tried to use object animations like this:
```
action = self.application.model.getObject(object_name, "steamfolktales").getAction("idle")
visual = action.get2dGfxVisual()
anim = visual.getAnimationByAngle(visual.getActionImageAngles()[0])
self.application.engine.getCursor().set(anim)
```
creating the cursor failed at first because Image::getSurface() returned NULL. Calling ImageManager::load() beforehand didn't help. But if retried a few times after a few seconds it started working for some reason. Possibly a bug in GLImage?

### CODE REVIEW

**Comment by helios2000** [comment]
Looks very good! Great that you added support for animations too and the missing log module.
Regarding the animation problem, you could add something like:
```
if (anim->getState() == IResource::RES_NOT_LOADED) {
    anim->load();
}
```
That should ensure that the images of the animations are loaded.

**Comment by Niektory** [comment]
Nope, getState() returns RES_LOADED, but I'm still getting a NULL surface.

**Comment by Niektory** [comment]
I can get the surface after calling ImageManager::reload() on the image.

**Comment by helios2000** [comment]
Yeah probably a bug in the Objectloader. I think you do use an atlas?

**Comment by helios2000** [comment]
I hope I've found and fixed the bug. Would great if you could test it.

**Comment by Niektory** [comment]
Still doesn't work.
It starts working after it has been rendered by the engine at least once, but not before that.
Here's the object file I'm trying with just in case:
```
<?xml version='1.0' encoding='UTF-8'?>
<assets>
	<object blocking="1" cellstack_position="0" id="Bush01_animated" namespace="steamfolktales" static="0">
		<action id="idle">
			<animation atlas="Bush01_animated.png" height="256" width="256" x_offset="-128" y_offset="-128">
				<direction delay="250" dir="0" frames="6" />
			</animation>
		</action>
		<action id="still">
			<animation atlas="Bush01_animated.png" height="256" width="256" x_offset="-128" y_offset="-128">
				<direction delay="250" dir="0" frames="1" />
			</animation>
		</action>
	</object>
</assets>
```

**Comment by helios2000** [comment]
Well, I fixed the problem that the animation was marked as loaded. If it's still not working with anim->load() there is another bug. Still strange, because under the hood all calls the same functions.

**Comment by Niektory** [comment]
Alright, I fixed it. Shared images were always marked as loaded even when the parent image was not loaded.

**Comment by helios2000** [comment]
Great :) When everything is ready, I can gladly merge it.

**Comment by Niektory** [comment]
It's ready.

**Pull request merged**
